sequenceDiagram
    participant C as Customer App
    participant G as API Gateway
    participant R as Ride Service
    participant P as Payment Service
    participant DB as payment_db
    participant MQ as RabbitMQ
    participant N as Notification Service
    participant RV as Review Service

    C->>G: Yeu cau thanh toan ride
    G->>P: POST /payments/intents
    P->>DB: Tao Fare va Payment
    DB-->>P: Luu giao dich PENDING/PROCESSING
    P-->>G: Tra payment intent / client secret
    G-->>C: Hien thi ket qua thanh toan

    C->>G: Xac nhan thanh toan thanh cong
    G->>P: webhook/mock webhook
    P->>DB: Cap nhat Payment COMPLETED
    P->>DB: Tao OutboxEvent
    P->>MQ: Publish payment event
    MQ->>N: Tao notification hoan tat chuyen di
    N-->>C: Gui thong bao

    C->>G: Tao review cho driver
    G->>RV: POST /reviews
    RV-->>G: Luu review
    G-->>C: Tra ket qua danh gia
