flowchart TB
    subgraph AUTH_DB[auth_db]
        U[users]
        RT[refresh_tokens]
        U --> RT
    end

    subgraph USER_DB[user_db]
        UP[user_profiles]
    end

    subgraph DRIVER_DB[driver_db]
        DR[drivers]
    end

    subgraph BOOKING_DB[booking_db]
        BK[Booking]
    end

    subgraph RIDE_DB[ride_db]
        R[Ride]
        RST[RideStateTransition]
        R --> RST
    end

    subgraph PAYMENT_DB[payment_db]
        F[Fare]
        PM[Payment]
        OB[OutboxEvent]
        F --> PM
        PM -. event .-> OB
    end

    subgraph NOTIFICATION_DB[notification_db - MongoDB]
        NT[notifications]
    end

    subgraph REVIEW_DB[review_db - MongoDB]
        RV[reviews]
    end

    subgraph REDIS[Redis]
        SG[surge:multiplier]
        DG[drivers:geo:online]
        OF[ride:offer:*]
        OD[ride:offered:*]
        RJ[ride:rejected:*]
    end

    U -. user_id .-> UP
    U -. user_id .-> DR
    U -. customerId .-> BK
    U -. customerId .-> R
    DR -. driverId .-> R
    R -. rideId .-> F
    R -. rideId .-> PM
    R -. rideId .-> RV
    BK -. bookingId .-> RV
    U -. userId .-> NT
    DR -. vi tri realtime .-> DG
    R -. offer state .-> OF
    R -. offered drivers .-> OD
    R -. rejected drivers .-> RJ
    BK -. doc surge .-> SG
    R -. doc surge .-> SG
